import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  OnboardingReady: undefined;
  PersonalInfo: undefined;
  HealthGoals: undefined;
  BirthDate: undefined;
  Gender: undefined;
  Weight: undefined;
  Height: undefined;
  BloodType: undefined;
  FitnessLevel: undefined;
  SleepLevel: undefined;
  ActivityPreference: undefined;
  Mood: undefined;
  Diet: undefined;
  Calories: undefined;
  Medication: undefined;
  MedicationList: undefined;
  MedicationNotFound: { searchedMedication: string };
  Allergy: undefined;
  MedicalConditions: undefined;
  MedicalConditionList: undefined;
  MedicalConditionSearch: undefined;
  CheckupFrequency: undefined;
  BodyAnalysis: undefined;
  BodyScan: undefined;
  ScanResults: { photoUri?: string } | undefined;
  AdditionalNotes: undefined;
  VoiceAIAnalysis: undefined;
  VoiceRecording: undefined;
  VoiceRecordingResults: { audioUri?: string } | undefined;
  Home: undefined;
};